feat(ci): added checkov scanning to scan the IaC files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,9 +10,39 @@ env:
   IMAGE_NAME: go-url-shortner
 
 jobs:
+  checkov_scan:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Install Checkov
+        run: pip install checkov
+
+      - name: Run Checkov on infra/
+        run: checkov -d infra/ -o json > checkov-report.json || true
+
+      - name: name: Upload Checkov report
+        uses: actions/upload-artifact@v4
+        with:
+          name: checkov-report
+          path: checkov-report.json
+
+      - name: Fail on critical Checkov findings (optional)
+        if: always()
+        run: |
+          # Check if the 'failed_checks' array has any elements
+          if jq -e '.results.failed_checks | length > 0' checkov-report.json >/dev/null 2>&1; then
+            echo "::error::Checkov found one or more failed infrastructure security checks."
+            # Uncomment the next line to fail CI when Checkov finds anything
+            # exit 1
+          else
+            echo "Checkov scan passed. No failed infrastructure checks found."
+          fi
+
   build_and_scan:
     runs-on: ubuntu-latest
-
+    
     services:
       redis:
         image: redis:6-alpine
@@ -111,25 +141,21 @@ jobs:
              echo "Trivy JSON file is empty or missing, assuming scan passed (no vulnerabilities found)."
           fi
 
-      - name: Log in into GitHub Container Registry
-        uses: docker/login-action@v3
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
         with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          role-to-assume: arn:aws:iam::398195329839:role/GitHubActionsECRPushRole
+          aws-region: us-east-1
 
-      - name: Push Docker image to registry
-        id: push_image
+      - name: Tag & Push to ECR
         env:
-          IMAGE_TAG: ${{ github.sha }}
+          ECR_REGISTRY: ${{ steps.configure_aws.outputs.account_id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
+          IMAGE: ${{ env.IMAGE_NAME }}:${{ github.sha }}
         run: |
-          REPO_LOWERCASE="${{ github.repository }}"
-          REPO_LOWERCASE="${REPO_LOWERCASE,,}"
-          IMAGE_URI_TAG="ghcr.io/${REPO_LOWERCASE}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}"
-          docker tag "${{ env.IMAGE_NAME }}:${IMAGE_TAG}" "${IMAGE_URI_TAG}"
-          IMAGE_DIGEST_REF=$(docker push "${IMAGE_URI_TAG}" | tail -n 1)
-
-          echo "IMAGE_DIGEST_REF=${IMAGE_DIGEST_REF}" >> $GITHUB_ENV
+          aws ecr describe-repositories --repository-names go-shortner || aws ecr create-repository --repository-name go-shortner
+          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
+          docker tag "${IMAGE}" "$ECR_REGISTRY/go-url-shortner:${{ github.sha }}"
+          docker push "$ECR_REGISTRY/go-url-shortner:${{ github.sha }}"
 
       - name: Install Cosign
         uses: sigstore/cosign-installer@v3.5.0
