fix(ci): add check step to check if ecr regisrty is empty

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -172,15 +172,17 @@ jobs:
 
       - name: Tag and Push the images to ECR
         id: push_image
-        env:
-          IMAGE_TAG: ${{ github.sha }}
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          IMAGE_NAME: ${{ env.IMAGE_NAME }}
         run: |
-          CLEAN_REGISTRY=$(echo "${ECR_REGISTRY_RAW}" | tr -d '\n' | xargs)
-          CLEAN_IMAGE_NAME=$(echo "${IMAGE_NAME}" | tr -d '\n' | xargs)
+          CLEAN_REGISTRY="${{ steps.login-ecr.outputs.regisrty }}"
+          CLEAN_IMAGE_NAME="${{ env.IMAGE_NAME }}"
+          IMAGE_TAG="${{ github.sha }}"
 
           ECR_URI_TAG="${CLEAN_REGISTRY}/${CLEAN_IMAGE_NAME}:${IMAGE_TAG}"
+          if [ -z "$CLEAN_REGISTRY" ]; then
+              echo "::error::ECR Registry URI is empty. Cannot tag image."
+              exit 1
+          fi
+          
           docker tag "${IMAGE_NAME}:${IMAGE_TAG}" "${ECR_URI_TAG}"
           IMAGE_DIGEST_REF=$(docker push "${ECR_URI_TAG}" | grep 'digest' | awk '{print $NF}')
           echo "ECR_URI_TAG_CLEAN=${ECR_URI_TAG}" >> $GITHUB_ENV
